### PR TITLE
Fix (#232): Removed reset zoom when game map changing

### PR DESCRIPTION
**Pull request by Fenex**

### CODE REVIEW

**Comment by stalkerg** [comment]
What about small worlds like xMok? 
Maybe better to use this factor? 
```
camera_zmin = camera_zmin*(xsize/xsize_old);
```

**Comment by Fenex** [comment]
> 
> 
> What about small worlds like xMok?
> Maybe better to use this factor?
>

Yeah, there was an error if viewport size is changing (when open inventory or press F1 to hide window's wrapper).
Now it looks like you can merge.

**Comment by stalkerg** [comment]
Did you check animation between worlds?

**Comment by Fenex** [comment]
I & @DiTolk played in passembloss mod, nothing weird.

**Comment by stalkerg** [comment]
I mean not in multiplayer.

**Comment by Fenex** [comment]
No, I didn't test in single mode. Why do you think that an animation 
will be different in single mode?

11.07.2020 12:23, Yury Zhuravlev пишет:
>
> I mean not in multiplayer.
>

**Comment by stalkerg** [comment]
Ok! Fine, thanks!

**Pull request merged**
