### PR TITLE
Make build cleaner

### PR DESCRIPTION
**Pull request by shamazmazum**
Hello. This pull request makes a build much cleaner (less warnings) when building with clang. The changes include:

* Add `-Wall` and `-Wextra` flags only when doing `DEBUG` build. Warnings produced with `-Wall -Wextra` are useful, but now they make a mess.
* Convert `if (res = foo()) { /* ... */ }` to `if ((res = foo()) { /* ... */ }`.
* Convert `if ((val == foo())) { /* ... */ }` to `if (val == foo()) { /* ... */ }`.
* Add `return 0;` to not implemented networking functions when they must return a value. Zero means a failure (judging on comments).
* Fix misused `abs()`. I've decided to keep C-functions rather than use `std::abs()` because it is a common style of the game's code.
* Fix dangling elses.
* Fix mixed LF and CRLF EOL style. Why do you prefer CRLF after all?

### CODE REVIEW

**Comment by shamazmazum** [comment]
I've just signed some weird agreement. I do it to the extent that it doesn't contradict GNU GPLv3 (I think it doesn't, but I am not a lawyer).

**Comment by shamazmazum** [comment]
The remaining warnings (https://travis-ci.com/github/shamazmazum/Vangers/jobs/322494247):

*  `if(!(*(buf -= 2) | *(buf -= 2))){` at `src/3d/optimize.cpp`. Typical UB. Do you know what does it suppose to mean?
*  `dy0 = dy <= 0 ? 1 << 16 : -1 << 16;` at `src/3d/optimize.cpp`. My guess it is `-(1<<16)`. Am I right?
* `if(kmap.size() != (int)(V_SIZE*H2_SIZE + V_SIZE),XS_BEG) {` at `src/terra/vmap.cpp`
My parser is broken.
* `if(res = getPassangerStats(es[j],ws[i])){` at `src/uvs/diagen.cpp` `res` is not used inside `if` body. Also it is overwritten just after it. Now it means just `if(getPassangerStats(es[j],ws[i]) != 0) {`

**Comment by NIR-Ginko** [comment]
This is a possible fix for error in my bug report: https://github.com/KranX/Vangers/issues/220 . Also it's nice to see HAIKU definitions. :)

**Comment by stalkerg** [comment]
> do it to the extent that it doesn't contradict GNU GPLv3 (I think it doesn't, but I am not a lawyer).

It's needed only to deploy in Steam and other channels where we can't use GPL.

**Comment by stalkerg** [comment]
Looks good for me. Thanks!

**Pull request merged**
