### PR TITLE
[CI, MinGW, Windows] Adds No BINARY_SCRIPT and Static Build

### PR DESCRIPTION
**Pull request by ZeeWanderer**
- Added No BINARY_SCRIPT build to Windows CI. Because having this build is required to update binary script resources. This build is done in the same instance where the normal build is built to reuse clunk and FFmpeg. Sure if done in parallel should not affect build time and current non-parallel impl actually extends build time somewhat but recompiling clulnk and FFmpeg just doesn't feel right since that is actually the longest build part. Thou if you deem it necessary changing to parallel is trivial. 
- Transitioned Windows MinGW builds to static linking. No more 'manual' deps dll copying! Dynamic linking is useful but not here, besides static build results in actually smaller bin size. ([1 //for Linux but is applicable here](https://drewdevault.com/dynlib.html))
- Added VS Cmake specific ignores

VS2019 CMake MinGW works surprisingly well thou clunk and FFmpeg need to be built and installed via MinGW shell manually. VS refuses to acknowledge CMakeLists in clunk repo.

### CODE REVIEW

**Comment by stalkerg** [comment]
I can't use static linking because in the Steam it's not a GPL license. 
Instead of a BINARY_SCRIPT option, I suppose will be better to make a script compiler in runtime without running the actual game. Something like we did for Russian/English languages.

**Comment by ZeeWanderer** [comment]
Oh ok. Thou macOS build is just temperamental https://github.com/ZeeWanderer/Vangers/runs/863280429 . Besides previous commits are fine and the commit it broke on has nothing to do with macOS.

So i guess this PR is unusable but I still think that until/if a resource compiler tool is implemented there should be an available build with BINARY_SCRIPT=NO. The question is do i place it in separate workflow or existing ones, and if in existing than in parallel or sequential?

**Comment by ZeeWanderer** [comment]
Ok so if i understand it right, you cant distribute SW with statically linked libs that are under GPL. clunk is MIT, FFmpeg is LGPL unless some parts are used. Also, you can grant steam a different license for your own software. GCC standard libs have an exception that allows static linking without GLP license. I understand little about licensing, never before had to bother but could you expand on your current situation in more detail if you have time? Btw I understand Russian as well.

**Comment by stalkerg** [comment]
Clunk is LGPL for our version... We do not support Clunk 2.0 under MIT. 
Looks like in industry we have consensus about it LGPL libraries we can only dynamic linking with not a GPL/LGPL libraries. 

> Besides previous commits are fine and the commit it broke on here has nothing to do with macOS. Or you don't mean CI?

it's fine now. 


> I understand little about licensing, never before had to bother but could you expand on your current situation in more detail if you have time? Btw I understand Russian as well.


Ping me in telegram https://t.me/stalkerg , please.

**Comment by stalkerg** [comment]
If you have time will be perfect to introduce headless mode for Vangers just to compile UI scripts.

**Pull request closed without merging**
