### PR TITLE
Replace define RUSSIAN_VERSION with argument '-russian'

### PR DESCRIPTION
**Pull request by caiiiycuk**
Hi. This is not very handy to switch language by recompiling code. This PR removes RUSSIAN_VERSION define with '-russian' command line argument.

Any feedback are welcome.

### CODE REVIEW

**Comment by stalkerg** [comment]
WOW! It's awesome, I many times before thinking about it... But how it's working with binary scripts?

**Comment by caiiiycuk** [comment]
Not sure what exactly you asked ) I tested this branch with -DBINARY_SCRIPT it works for English version from steam out of the box. And for Russian version after one run without BINARY_SCRIPT. Actually this is just mechanical replacement of define with `lang()` function.

I think everything should works as before. I am not sure about diagen system, because I don't know how to check it.

**Comment by stalkerg** [comment]
unfortunately, BINARY_SCRIPT=OFF not working correctly, but I will look into.

**Comment by stalkerg** [comment]
Hmm, I don't know what it was but now it is working fine. 
Thanks!

**Comment by caiiiycuk** [comment]
Wow! Awesome!

**Pull request merged**
